/**
 * Realistic Mock Dataset matching exact Screenshot 2
 */

export const SAMPLE_QUESTION_PAPER_NAME = "Class_10_Biology_Unit_Test.pdf";
export const SAMPLE_ANSWER_SHEET_NAME = "student_1_answer_sheet.pdf";

export const MOCK_QUESTIONS = [
  {
    id: "q1",
    qNo: "1",
    subPart: null,
    text: "Which blood vessel carries blood away from the heart?",
    maxMarks: 2,
    page: 1,
    bbox: [5, 8, 15, 92],
  },
  {
    id: "q2",
    qNo: "2",
    subPart: null,
    text: "Which of the following organelles is primarily involved in photosynthesis?",
    maxMarks: 2,
    page: 1,
    bbox: [18, 8, 38, 92],
  },
  {
    id: "q3",
    qNo: "3",
    subPart: null,
    text: "Explain the role of chloroplasts in photosynthesis, naming the main pigments involved and briefly outlining the two major stages of the process.",
    maxMarks: 2,
    page: 1,
    bbox: [40, 8, 55, 92],
  },
  {
    id: "q4",
    qNo: "4",
    subPart: null,
    text: "Describe the flow of blood through the human heart starting from the right atrium and ending at the aorta; include the names of valves crossed.",
    maxMarks: 2,
    page: 2,
    bbox: [5, 8, 20, 92],
  },
  {
    id: "q5",
    qNo: "5",
    subPart: null,
    text: "Draw a labelled diagram of an alveolus showing capillaries and air space (label alveolar sac, capillary, and direction of gas exchange).",
    maxMarks: 2,
    page: 2,
    bbox: [22, 8, 38, 92],
  },
  {
    id: "q6",
    qNo: "6",
    subPart: null,
    text: "Draw a neat labelled diagram of the human digestive system (stomach, small intestine, large intestine, liver, pancreas) and label the site where most absorption occurs.",
    maxMarks: 5,
    page: 2,
    bbox: [40, 8, 60, 92],
  },
  {
    id: "q7",
    qNo: "7",
    subPart: null,
    text: "Draw and label a nephron (Bowman's capsule, glomerulus, proximal tubule, loop of Henle, distal tubule, collecting duct).",
    maxMarks: 5,
    page: 3,
    bbox: [5, 8, 25, 92],
  },
  {
    id: "q8",
    qNo: "8",
    subPart: null,
    text: "Explain the structural differences between palisade mesophyll and spongy mesophyll and state how each structure aids its function in the leaf.",
    maxMarks: 5,
    page: 3,
    bbox: [28, 8, 48, 92],
  },
  {
    id: "q9",
    qNo: "9",
    subPart: null,
    text: "Describe the process of transpiration in plants in two to three sentences and name two environmental factors that increase its rate.",
    maxMarks: 5,
    page: 3,
    bbox: [50, 8, 68, 92],
  },
  {
    id: "q10",
    qNo: "10",
    subPart: null,
    text: "Explain how the structure of xylem vessels facilitates water transport in plants (mention one structural feature and its role).",
    maxMarks: 5,
    page: 4,
    bbox: [5, 8, 22, 92],
  },
  {
    id: "q11_a",
    qNo: "11",
    subPart: "a.",
    text: "A diagram shows two potted plants — Plant A in bright light with broad green leaves, Plant B kept in dim light with pale, elongated leaves.",
    maxMarks: 2,
    page: 4,
    bbox: [24, 8, 40, 92],
  },
  {
    id: "q11_b",
    qNo: "11",
    subPart: "b.",
    text: "Suggest one practical measure to help Plant B recover.",
    maxMarks: 3,
    page: 4,
    bbox: [42, 8, 55, 92],
  },
  {
    id: "q12",
    qNo: "12",
    subPart: null,
    text: "A resting person has tidal volume (air per breath) of 0.5 L and breathes 12 times per minute.",
    maxMarks: 5,
    page: 4,
    bbox: [58, 8, 72, 92],
  },
  {
    id: "q13",
    qNo: "13",
    subPart: null,
    text: "If dead space is 0.15 L per breath, calculate the alveolar ventilation per minute. Show working.",
    maxMarks: 5,
    page: 4,
    bbox: [74, 8, 90, 92],
  }
];

export const MOCK_ANSWERS = [
  {
    id: "ans_q1",
    questionId: "q1",
    status: "matched",
    confidence: 0.98,
    page: 1,
    bbox: { ymin: 4, xmin: 5, ymax: 30, xmax: 95 },
    extractedText: "Ans 1: Photosynthesis is the process used by green plants and some other organisms to convert light energy into chemical energy. 6CO2 + 6H2O -> C6H12O6 + 6O2.",
    marks: 2,
    maxMarks: 2,
    verdict: "correct",
    feedback: "Accurate definition and balanced chemical equation."
  },
  {
    id: "ans_q2",
    questionId: "q2",
    status: "matched",
    confidence: 0.96,
    page: 1,
    bbox: { ymin: 44, xmin: 5, ymax: 68, xmax: 95 },
    extractedText: "Ans 2: The process mainly occurs in the chloroplast of the plant cell. It has two main stages: 1. Light reaction - Captures light energy. 2. Dark reaction - Uses energy to make glucose.",
    marks: 2,
    maxMarks: 2,
    verdict: "correct",
    feedback: "Excellent work! You correctly identified the chloroplast as the organelle responsible for photosynthesis. Keep it up!"
  },
  {
    id: "ans_q3",
    questionId: "q3",
    status: "matched",
    confidence: 0.92,
    page: 1,
    bbox: { ymin: 72, xmin: 5, ymax: 95, xmax: 95 },
    extractedText: "Ans 3: Chloroplasts contain chlorophyll pigment which absorbs sunlight during the light phase.",
    marks: 2,
    maxMarks: 2,
    verdict: "correct",
    feedback: "Well answered!"
  },
  {
    id: "ans_q4",
    questionId: "q4",
    status: "matched",
    confidence: 0.20,
    page: 2,
    bbox: { ymin: 5, xmin: 5, ymax: 20, xmax: 95 },
    extractedText: "[Incomplete / Incorrect answer]",
    marks: 0,
    maxMarks: 2,
    verdict: "incorrect",
    feedback: "Incorrect sequence of valves and chambers in cardiac blood flow."
  },
  {
    id: "ans_q5",
    questionId: "q5",
    status: "matched",
    confidence: 0.95,
    page: 2,
    bbox: { ymin: 22, xmin: 5, ymax: 45, xmax: 95 },
    extractedText: "Ans 5: Alveolar gas exchange diagram.",
    marks: 2,
    maxMarks: 2,
    verdict: "correct",
    feedback: "Neat diagram with all labels."
  },
  {
    id: "ans_q6",
    questionId: "q6",
    status: "matched",
    confidence: 0.88,
    page: 2,
    bbox: { ymin: 48, xmin: 5, ymax: 75, xmax: 95 },
    extractedText: "Ans 6: Digestive system diagram.",
    marks: 4,
    maxMarks: 5,
    verdict: "partial",
    feedback: "Good diagram, missed labeling the pancreas specifically."
  },
  {
    id: "ans_q7",
    questionId: "q7",
    status: "matched",
    confidence: 0.96,
    page: 3,
    bbox: { ymin: 5, xmin: 5, ymax: 30, xmax: 95 },
    extractedText: "Ans 7: Nephron diagram and Bowman's capsule.",
    marks: 5,
    maxMarks: 5,
    verdict: "correct",
    feedback: "Complete and accurate diagram."
  },
  {
    id: "ans_q8",
    questionId: "q8",
    status: "matched",
    confidence: 0.75,
    page: 3,
    bbox: { ymin: 32, xmin: 5, ymax: 55, xmax: 95 },
    extractedText: "Ans 8: Palisade cells are elongated; spongy mesophyll has air spaces.",
    marks: 3,
    maxMarks: 5,
    verdict: "partial",
    feedback: "Mentioned structure, but missed explaining gas exchange function in detail."
  },
  {
    id: "ans_q9",
    questionId: "q9",
    status: "matched",
    confidence: 0.94,
    page: 3,
    bbox: { ymin: 58, xmin: 5, ymax: 85, xmax: 95 },
    extractedText: "Ans 9: Transpiration is loss of water vapor from stomata.",
    marks: 5,
    maxMarks: 5,
    verdict: "correct",
    feedback: "Clear description and correct environmental factors."
  },
  {
    id: "ans_q10",
    questionId: "q10",
    status: "matched",
    confidence: 0.90,
    page: 4,
    bbox: { ymin: 5, xmin: 5, ymax: 25, xmax: 95 },
    extractedText: "Ans 10: Xylem vessel walls are lignified for support.",
    marks: 4,
    maxMarks: 5,
    verdict: "partial",
    feedback: "Good point about lignin."
  },
  {
    id: "ans_q11_a",
    questionId: "q11_a",
    status: "matched",
    confidence: 0.95,
    page: 4,
    bbox: { ymin: 28, xmin: 5, ymax: 48, xmax: 95 },
    extractedText: "Ans 11a: Plant B suffers from etiolation due to lack of light.",
    marks: 2,
    maxMarks: 2,
    verdict: "correct",
    feedback: "Correct observation."
  },
  {
    id: "ans_q11_b",
    questionId: "q11_b",
    status: "matched",
    confidence: 0.60,
    page: 4,
    bbox: { ymin: 50, xmin: 5, ymax: 70, xmax: 95 },
    extractedText: "Ans 11b: Move plant B near a window.",
    marks: 1,
    maxMarks: 3,
    verdict: "partial",
    feedback: "Correct suggestion, but missing explanation of light restoration."
  },
  {
    id: "ans_q12",
    questionId: "q12",
    status: "matched",
    confidence: 0.88,
    page: 4,
    bbox: { ymin: 72, xmin: 5, ymax: 85, xmax: 95 },
    extractedText: "Ans 12: Pulmonary ventilation = 0.5 * 12 = 6.0 L/min.",
    marks: 4,
    maxMarks: 5,
    verdict: "partial",
    feedback: "Accurate calculation."
  },
  {
    id: "ans_q13",
    questionId: "q13",
    status: "matched",
    confidence: 0.92,
    page: 4,
    bbox: { ymin: 87, xmin: 5, ymax: 98, xmax: 95 },
    extractedText: "Ans 13: Alveolar ventilation = (0.5 - 0.15) * 12 = 4.2 L/min.",
    marks: 4,
    maxMarks: 5,
    verdict: "partial",
    feedback: "Correct formula and working."
  }
];

export const UNANSWERED_QUESTIONS = [];

export const MOCK_SUMMARY = {
  totalMarksObtained: 41,
  totalMaxMarks: 51,
  percentage: 80.4,
  attemptedCount: 14,
  totalQuestions: 14,
  unansweredCount: 0,
  unmatchedCount: 0,
  strengths: ["Plant Biology & Photosynthesis", "Calculations & Pulmonary Ventilation"],
  weakAreas: ["Human Cardiac Blood Flow Valves"],
  overallTeacherNote: "Madhur's student demonstrated high accuracy in Biology & Physiology concepts with neat diagrams. Heart valve sequence needs review."
};
